[2023-07-28T14:19:02.618+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-28T14:19:02.627+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-28T14:19:02.627+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-28T14:19:02.628+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-28T14:19:02.628+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-28T14:19:02.641+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): t2> on 2023-07-27 00:00:00+00:00
[2023-07-28T14:19:02.645+0000] {standard_task_runner.py:55} INFO - Started process 2925 to run task
[2023-07-28T14:19:02.648+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 't2', 'scheduled__2023-07-27T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpscr1p51u']
[2023-07-28T14:19:02.648+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask t2
[2023-07-28T14:19:02.697+0000] {task_command.py:376} INFO - Running <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [running]> on host b81352b01223
[2023-07-28T14:19:02.753+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2023-07-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-27T00:00:00+00:00
[2023-07-28T14:19:02.754+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-07-28T14:19:02.762+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=t2, execution_date=20230727T000000, start_date=20230728T141902, end_date=20230728T141902
[2023-07-28T14:19:02.779+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-07-28T14:19:02.797+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-07-28T14:24:11.109+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-28T14:24:11.117+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [queued]>
[2023-07-28T14:24:11.117+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-07-28T14:24:11.118+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-07-28T14:24:11.118+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-07-28T14:24:11.130+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): t2> on 2023-07-27 00:00:00+00:00
[2023-07-28T14:24:11.134+0000] {standard_task_runner.py:55} INFO - Started process 3178 to run task
[2023-07-28T14:24:11.136+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 't2', 'scheduled__2023-07-27T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpen3b24f8']
[2023-07-28T14:24:11.137+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask t2
[2023-07-28T14:24:11.184+0000] {task_command.py:376} INFO - Running <TaskInstance: xcom_dag.t2 scheduled__2023-07-27T00:00:00+00:00 [running]> on host b81352b01223
[2023-07-28T14:24:11.238+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=t2
AIRFLOW_CTX_EXECUTION_DATE=2023-07-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-27T00:00:00+00:00
[2023-07-28T14:24:11.239+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/xcom_dag.py", line 11, in _t2
    print(ti.xcom_pull(key='my_key', task_id = 't1'))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2023-07-28T14:24:11.247+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=xcom_dag, task_id=t2, execution_date=20230727T000000, start_date=20230728T142411, end_date=20230728T142411
[2023-07-28T14:24:11.256+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task t2 (xcom_pull() got an unexpected keyword argument 'task_id'; 3178)
[2023-07-28T14:24:11.268+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-07-28T14:24:11.290+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
